package mod.mitecreation.init;

import huix.glacier.api.entrypoint.IGameRegistry;
import huix.glacier.api.registry.MinecraftRegistry;
import mod.mitecreation.block.*;
import mod.mitecreation.block.ore.normal.*;
import mod.mitecreation.client.audio.CTStepSound;
import mod.mitecreation.client.audio.CTStepSoundDeepslateBrick;
import mod.mitecreation.creativetab.CreativeTabsCreationBlock;
import mod.mitecreation.creativetab.CreativeTabsCreationItem;
import mod.mitecreation.creativetab.CreativeTabsCreationTool;
import mod.mitecreation.item.ItemCTFishingRod;
import mod.mitecreation.item.ItemCTSnowBerryBowl;
import mod.mitecreation.item.ItemCTRawNugget;
import mod.mitecreation.material.CTMaterials;
import moddedmite.rustedironcore.api.block.*;
import moddedmite.rustedironcore.api.item.IngotItem;
import net.minecraft.*;
import net.xiaoyu233.fml.api.block.StrongBoxBlock;
import net.xiaoyu233.fml.api.item.NuggetItem;
import net.xiaoyu233.fml.reload.utils.IdUtil;

import static net.minecraft.Block.*;
import static net.xiaoyu233.fml.util.ReflectHelper.createInstance;

public class CTRegistryInit implements IGameRegistry {
    public static final CreativeTabs tabCreationBlock = new CreativeTabsCreationBlock();
    public static final CreativeTabs tabCreationItem = new CreativeTabsCreationItem();
    public static final CreativeTabs tabCreationTool = new CreativeTabsCreationTool();

    public static final StepSound soundDeepslateFootstep = new CTStepSound(CreationModInit.RESOURCEID + "deepslate", 1.0F, 1.0F);
    public static final StepSound soundDeepslateBrickFootstep = new CTStepSoundDeepslateBrick(CreationModInit.RESOURCEID + "deepslate_bricks", 1.0F, 1.0F);

    public static final MinecraftRegistry registry = new MinecraftRegistry(CreationModInit.NAMESPACE).initAutoItemRegister();
    
    public static Block rustedIronBlock;
    public static final BlockAnvil anvilRustedIron;
    public static final Block oreTungsten;
    public static final Block blockTungsten;
    public static final Block fenceTungsten;
    public static final Block doorTungsten;
    public static final BlockAnvil anvilTungsten;
    public static final BlockCTDeepStaleBrick deepStaleBrick;
    public static final BLockCTDeepSlateMagma deepStaleMagma;
    public static final Block cobbledDeepStale;
    public static final Block stairsCobbleDeepSlate;
    public static final Block stairsDeepSlateBrick;
    public static final BlockCTSandGravel gravelSand;
    public static final BlockCTDeepSlateGravel gravelDeepSlate;
    public static final Block cobbleDeepStaleWall;
    public static final Block deepStaleBrickWall;
    public static final Block deepSlate;
    public static final BlockCTCobbleDeepSlateSlabGroup cobbledDeepStaleSingleSlab;
    public static final BlockCTDeepSlateDoubleSlab cobbledDeepStaleDoubleSlab;
    public static final BlockCTDeepSlateBrickSlabGroup deepStaleBrickSingleSlab;
    public static final BlockCTDeepSlateDoubleSlab deepStaleBrickDoubleSlab;
    public static final BlockCTAncientRelict ancientRelict;
    public static final WorkbenchBlock tungstenWorkBench;
    public static final Block oreIronDeepslate;
    public static final Block oreCoalDeepslate;
    public static final Block oreLapisDeepslate;
    public static final Block oreDiamondDeepslate;
    public static final Block oreEmeraldDeepslate;
    public static final Block oreCopperDeepslate;
    public static final Block oreSilverDeepslate;
    public static final Block oreMithrilDeepslate;
    public static final Block oreAdamantiumDeepslate;
    public static final Block oreTungstenDeepslate;
    public static final Block oreGoldDeepslate;
    public static final Block oreRedstoneDeepslate;
    public static final BlockCTDeepslateSilverFish deepslateSilverFish;
    public static final Block chestTungsten;
    public static final Block oreRedstoneDeepslateGlowing;
    public static final BlockCTWood peachPlanks;
    public static final BlockCTLog peachWood;
    public static final BlockCTLeaves peachLeaves;
    public static final Block peachSapling;
    public static final BlockCTPeachPlanksSlabGroup peachPlanksSingleSlab;
    public static final BlockCTPeachPlanksDoubleSlab peachPlanksDoubleSlab;
    public static final Block stairsPeachPlanks;
    public static final BlockCTSnowBerry snowBerry;
    public static final Block basalt;

    public static final ItemCoin coinIron = (ItemCoin) createInstance(ItemCoin.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), Material.iron).setCreativeTab(tabCreationItem);
    public static final ItemCoin coinRustedIron = (ItemCoin) createInstance(ItemCoin.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), Material.rusted_iron).setCreativeTab(tabCreationItem);
    public static final NuggetItem rustedIronNugget = (NuggetItem) new NuggetItem(IdUtil.getNextItemID(), Material.rusted_iron).setCreativeTab(tabCreationItem);
    public static final IngotItem ingotRustedIron = (IngotItem) new IngotItem(IdUtil.getNextItemID(), Material.rusted_iron).setMaxStackSize(8).setCreativeTab(tabCreationItem);
    public static ItemCTFishingRod fishingRodRustedIron = (ItemCTFishingRod)(new ItemCTFishingRod(IdUtil.getNextItemID(), Material.rusted_iron)).setUnlocalizedName("fishingRod").setCreativeTab(tabCreationTool);
    public static final ItemCTRawNugget rawRustedIronNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.rusted_iron).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawCopperNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.copper).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawSilverNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.silver).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawGoldNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.gold).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawAncientMetalNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.ancient_metal).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawTungstenNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawMithrilNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.mithril).setCreativeTab(tabCreationItem);
    public static final ItemCTRawNugget rawAdamantiumNugget = (ItemCTRawNugget) new ItemCTRawNugget(IdUtil.getNextItemID(), Material.adamantium).setCreativeTab(tabCreationItem);
    public static final ItemNugget tungstenNugget = (ItemNugget) createInstance(ItemNugget.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationItem);
    public static final Item ingotTungsten = createInstance(ItemIngot.class,new Class[]{int.class, Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setXPReward(25).setCreativeTab(tabCreationItem);
    public static final ItemWarHammer warHammerTungsten = (ItemWarHammer) createInstance(ItemWarHammer.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemBattleAxe battleAxeTungsten = (ItemBattleAxe) createInstance(ItemBattleAxe.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemSword swordTungsten = (ItemSword) createInstance(ItemSword.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemDagger daggerTungsten = (ItemDagger) createInstance(ItemDagger.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemPickaxe pickaxeTungsten = (ItemPickaxe) createInstance(ItemPickaxe.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemShovel shovelTungsten = (ItemShovel) createInstance(ItemShovel.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemAxe axeTungsten = (ItemAxe) createInstance(ItemAxe.class, new Class[]{int.class, Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemHoe hoeTungsten = (ItemHoe) createInstance(ItemHoe.class, new Class[]{int.class ,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemKnife knifeTungsten = (ItemKnife) createInstance(ItemKnife.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemMattock mattockTungsten = (ItemMattock) createInstance(ItemMattock.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemScythe scytheTungsten = (ItemScythe) createInstance(ItemScythe.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemShears shearsTungsten = (ItemShears) createInstance(ItemShears.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemHatchet hatchetTungsten = (ItemHatchet) createInstance(ItemHatchet.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static ItemCTFishingRod fishingRodTungsten = (ItemCTFishingRod)(new ItemCTFishingRod(IdUtil.getNextItemID(), CTMaterials.tungsten)).setUnlocalizedName("fishingRod").setCreativeTab(tabCreationTool);
    public static final ItemArmor helmetTungsten = (ItemArmor) new ItemHelmet(IdUtil.getNextItemID(), CTMaterials.tungsten,false).setCreativeTab(tabCreationTool);
    public static final ItemArmor helmetChainTungsten = (ItemArmor) new ItemHelmet(IdUtil.getNextItemID(), CTMaterials.tungsten,true).setCreativeTab(tabCreationTool);
    public static final ItemArmor plateTungsten = (ItemArmor) new ItemCuirass(IdUtil.getNextItemID(), CTMaterials.tungsten,false).setCreativeTab(tabCreationTool);
    public static final ItemArmor plateChainTungsten = (ItemArmor) new ItemCuirass(IdUtil.getNextItemID(), CTMaterials.tungsten,true).setCreativeTab(tabCreationTool);
    public static final ItemArmor legsTungsten = (ItemArmor) new ItemLeggings(IdUtil.getNextItemID(), CTMaterials.tungsten,false).setCreativeTab(tabCreationTool);
    public static final ItemArmor legsChainTungsten = (ItemArmor) new ItemLeggings(IdUtil.getNextItemID(), CTMaterials.tungsten,true).setCreativeTab(tabCreationTool);
    public static final ItemArmor bootsTungsten = (ItemArmor) new ItemBoots(IdUtil.getNextItemID(), CTMaterials.tungsten,false).setCreativeTab(tabCreationTool);
    public static final ItemArmor bootsChainTungsten = (ItemArmor) new ItemBoots(IdUtil.getNextItemID(), CTMaterials.tungsten,true).setCreativeTab(tabCreationTool);
    public static final Item doorTungstenItem = new ItemDoor(IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationBlock);
    public static final ItemChain chainTungsten = (ItemChain) createInstance(ItemChain.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationItem);
    public static final ItemCoin coinTungsten = (ItemCoin) createInstance(ItemCoin.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationItem);
    public static final ItemArrow arrowTungsten = (ItemArrow) new ItemArrow(IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemBucket tungstenBucket = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), CTMaterials.tungsten, null).setCreativeTab(tabCreationTool);
    public static final ItemBucket tungstenBucketWater = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), CTMaterials.tungsten, Material.water).setContainerItem(tungstenBucket).setCreativeTab(tabCreationTool);
    public static final ItemBucket tungstenBucketLava = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), CTMaterials.tungsten, Material.lava).setContainerItem(tungstenBucket).setCreativeTab(tabCreationTool);
    public static final ItemBucket tungstenBucketStone = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), CTMaterials.tungsten, Material.stone).setContainerItem(tungstenBucket).setCreativeTab(tabCreationTool);
    public static final ItemBucketMilk tungstenBucketMilk = (ItemBucketMilk) (new ItemBucketMilk(IdUtil.getNextItemID(), CTMaterials.tungsten)).setContainerItem(tungstenBucket).setCreativeTab(tabCreationTool);
//    public static final Item rustedIronItemBlock = new ItemBlock(rustedIronBlock).setMaxStackSize(4).setCreativeTab(tabCreationBlock);
    public static final ItemClub clubStone = (ItemClub) createInstance(ItemClub.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.stone).setCreativeTab(tabCreationTool);
    public static final ItemDagger daggerStone = (ItemDagger) createInstance(ItemDagger.class,new Class[]{int.class,Material.class},IdUtil.getNextItemID(), CTMaterials.stone).setCreativeTab(tabCreationTool);
    public static final ItemBucket woodBucketEmpty = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), Material.wood,null).setCreativeTab(tabCreationTool);
    public static final ItemBucket woodBucketWater = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), Material.wood, Material.water).setContainerItem(woodBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemBucketMilk woodBucketMilk = (ItemBucketMilk) new ItemBucketMilk(IdUtil.getNextItemID(), Material.wood).setContainerItem(woodBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemBucket rustedIronBucketEmpty = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), Material.rusted_iron, null).setCreativeTab(tabCreationTool);
    public static final ItemBucket rustedIronBucketWater = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), Material.rusted_iron, Material.water).setContainerItem(rustedIronBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemBucket rustedIronBucketLava = (ItemBucket)new ItemBucket(IdUtil.getNextItemID(), Material.rusted_iron, Material.lava).setContainerItem(rustedIronBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemBucket rustedIronBucketStone = (ItemBucket) new ItemBucket(IdUtil.getNextItemID(), Material.rusted_iron, Material.stone).setContainerItem(rustedIronBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemBucketMilk rustedIronBucketMilk = (ItemBucketMilk) (new ItemBucketMilk(IdUtil.getNextItemID(), Material.rusted_iron)).setContainerItem(rustedIronBucketEmpty).setCreativeTab(tabCreationTool);
    public static final ItemSword swordEmerald = (ItemSword) createInstance(ItemSword.class ,new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), Material.emerald).setCreativeTab(tabCreationTool);
    public static final ItemSword swordDiamond = (ItemSword) createInstance(ItemSword.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), Material.diamond).setCreativeTab(tabCreationTool);
    public static final ItemHorseArmor horseArmorTungsten = (ItemHorseArmor) createInstance(ItemHorseArmor.class,new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.tungsten).setCreativeTab(tabCreationTool);
    public static final ItemFood peach = (ItemFood) (new ItemFood(IdUtil.getNextItemID(), Material.fruit, 2, 1, 1000, false, false, true, "peach")).setPlantProduct().setCreativeTab(tabCreationItem);
    public static final ItemShovel shovelPeachWood = (ItemShovel) createInstance(ItemShovel.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.peachWood).setCreativeTab(tabCreationTool);
    public static final ItemSword swordPeachWood = (ItemSword) createInstance(ItemSword.class, new Class[]{int.class, Material.class}, IdUtil.getNextItemID(), CTMaterials.peachWood).setCreativeTab(tabCreationTool);
    public static final ItemFood snowBerries = (ItemFood) (new ItemFood(IdUtil.getNextItemID(), Material.fruit, 1, 2, 500, false, false, true, "snow_berries")).setPotionEffect(Potion.poison.id, 10, 0, 0.4F).setPlantProduct().setCreativeTab(tabCreationItem);
    public static final ItemCTSnowBerryBowl snowBerryPorridge = (ItemCTSnowBerryBowl) (new ItemCTSnowBerryBowl(IdUtil.getNextItemID(), Material.fruit, "snow_berry_stew")).setFoodValue(3, 2, 250, false, false, true).setPlantProduct().setCreativeTab(tabCreationItem);

    private void registerItem(String resource, String name, Item item) {
        resource = CreationModInit.RESOURCEID + resource;
        registry.registerItem(resource, name, item);
    }

    private void registerBlock(Block block, String resource, String name) {
        resource = CreationModInit.RESOURCEID + resource;
        registry.registerBlock(block, resource, name);
    }

    private void registerBlock(Block block, String resource) {
        resource = CreationModInit.RESOURCEID + resource;
        registry.registerBlock(block, resource);
    }

    private void registerBlockAnvil(BlockAnvil block, String resource, String name) {
        resource = CreationModInit.RESOURCEID + resource;
        registry.registerBlockAnvil(block, resource, name);
    }

    @Override
    public void onGameRegistry() {
        //Register Items Heat Level
//        registry.registerItemHeatLevel(rawCopperNugget.itemID, 1);
//        registry.registerItemHeatLevel(rawSilverNugget.itemID, 1);
//        registry.registerItemHeatLevel(rawGoldNugget.itemID, 1);
//        registry.registerItemHeatLevel(rawRustedIronNugget.itemID, 2);
//        registry.registerItemHeatLevel(rustedIronNugget.itemID, 2);
//        registry.registerItemHeatLevel(rawAncientMetalNugget.itemID, 2);
//        registry.registerItemHeatLevel(rawMithrilNugget.itemID, 3);
//        registry.registerItemHeatLevel(rawTungstenNugget.itemID, 3);
//        registry.registerItemHeatLevel(rawAdamantiumNugget.itemID, 4);

        //Register Items
        registry.registerItem("coins/iron", "coinIron",  coinIron);
        registerItem("coins/rusted_iron", "coinRustedIron", coinRustedIron);
        registerItem("nuggets/rusted_iron", "rustedIronNugget", rustedIronNugget);
        registerItem("ingots/rusted_iron", "ingotRustedIron", ingotRustedIron);
        registerItem("fishing_rods/rusted_iron_uncast", "fishingRodRustedIron", fishingRodRustedIron);
//        registerItem("rusted_iron_block", rustedIronItemBlock);
        registerItem("ingots/tungsten", "ingotTungsten", ingotTungsten);
        registerItem("nuggets/tungsten", "tungstenNugget", tungstenNugget);
        registerItem("armor/tungsten_helmet", "helmetTungsten", helmetTungsten);
        registerItem("armor/tungsten_chestplate", "plateTungsten", plateTungsten);
        registerItem("armor/tungsten_leggings", "legsTungsten", legsTungsten);
        registerItem("armor/tungsten_boots", "bootsTungsten", bootsTungsten);
        registerItem("armor/tungsten_chainmail_helmet", "helmetChainTungsten", helmetChainTungsten);
        registerItem("armor/tungsten_chainmail_chestplate", "plateChainTungsten", plateChainTungsten);
        registerItem("armor/tungsten_chainmail_leggings", "legsChainTungsten", legsChainTungsten);
        registerItem("armor/tungsten_chainmail_boots", "bootsChainTungsten", bootsChainTungsten);
        registerItem("armor/horse/tungsten", "horseArmorTungsten", horseArmorTungsten);
        registerItem("tools/tungsten/tungsten_battle_axe", "battleAxeTungsten", battleAxeTungsten);
        registerItem("tools/tungsten/tungsten_dagger", "daggerTungsten", daggerTungsten);
        registerItem("tools/tungsten/tungsten_sword", "swordTungsten", swordTungsten);
        registerItem("tools/tungsten/tungsten_war_hammer", "warHammerTungsten", warHammerTungsten);
        registerItem("tools/tungsten/tungsten_axe", "axeTungsten", axeTungsten);
        registerItem("tools/tungsten/tungsten_hatchet", "hatchetTungsten", hatchetTungsten);
        registerItem("tools/tungsten/tungsten_hoe", "hoeTungsten", hoeTungsten);
        registerItem("tools/tungsten/tungsten_knife", "knifeTungsten", knifeTungsten);
        registerItem("tools/tungsten/tungsten_pickaxe", "pickaxeTungsten", pickaxeTungsten);
        registerItem("tools/tungsten/tungsten_mattock", "mattockTungsten", mattockTungsten);
        registerItem("tools/tungsten/tungsten_scythe", "scytheTungsten", scytheTungsten);
        registerItem("tools/tungsten/tungsten_shears", "shearsTungsten", shearsTungsten);
        registerItem("tools/tungsten/tungsten_shovel", "shovelTungsten", shovelTungsten);
        registerItem("fishing_rods/tungsten_uncast", "fishingRodTungsten", fishingRodTungsten);
        registerItem("doors/tungsten", "doorTungsten", doorTungstenItem);
        registerItem("chains/tungsten", "chainTungsten", chainTungsten);
        registerItem("coins/tungsten", "coinTungsten", coinTungsten);
        registerItem("arrows/tungsten", "arrowTungsten", arrowTungsten);
        registerItem("buckets/tungsten/empty", "tungstenBucket", tungstenBucket);
        registerItem("buckets/tungsten/lava", "tungstenBucketLava", tungstenBucketLava);
        registerItem("buckets/tungsten/milk", "tungstenBucketMilk", tungstenBucketMilk);
        registerItem("buckets/tungsten/stone", "tungstenBucketStone", tungstenBucketStone);
        registerItem("buckets/tungsten/water", "tungstenBucketWater", tungstenBucketWater);
        registerItem("raw_nuggets/rusted_iron", "rawRustedIronNugget", rawRustedIronNugget);
        registerItem("raw_nuggets/copper", "rawCopperNugget", rawCopperNugget);
        registerItem("raw_nuggets/silver", "rawSilverNugget", rawSilverNugget);
        registerItem("raw_nuggets/gold", "rawGoldNugget", rawGoldNugget);
        registerItem("raw_nuggets/ancient_metal", "rawAncientMetalNugget", rawAncientMetalNugget);
        registerItem("raw_nuggets/tungsten", "rawTungstenNugget", rawTungstenNugget);
        registerItem("raw_nuggets/mithril", "rawMithrilNugget", rawMithrilNugget);
        registerItem("raw_nuggets/adamantium", "rawAdamantiumNugget", rawAdamantiumNugget);
        registerItem("tools/stone/stone_club", "clubStone", clubStone);
        registerItem("tools/stone/stone_dagger", "daggerStone", daggerStone);
        registerItem("buckets/wood/empty", "woodBucketEmpty", woodBucketEmpty);
        registerItem("buckets/wood/water", "woodBucketWater", woodBucketWater);
        registerItem("buckets/wood/milk", "woodBucketMilk", woodBucketMilk);
        registerItem("buckets/rusted_iron/empty", "rustedIronBucketEmpty", rustedIronBucketEmpty);
        registerItem("buckets/rusted_iron/lava", "rustedIronBucketLava", rustedIronBucketLava);
        registerItem("buckets/rusted_iron/milk", "rustedIronBucketMilk", rustedIronBucketMilk);
        registerItem("buckets/rusted_iron/stone", "rustedIronBucketStone", rustedIronBucketStone);
        registerItem("buckets/rusted_iron/water", "rustedIronBucketWater", rustedIronBucketWater);
        registerItem("tools/emerald/emerald_sword", "swordEmerald", swordEmerald);
        registerItem("tools/diamond/diamond_sword", "swordDiamond", swordDiamond);
        registerItem("food/peach", "peach", peach);
        registerItem("tools/peach_wood/peach_wood_shovel", "shovelPeachWood", shovelPeachWood);
        registerItem("tools/peach_wood/peach_wood_sword", "swordPeachWood", swordPeachWood);
        registerItem("food/snow_berries", "snowBerries", snowBerries);
        registerItem("bowl/snow_berry", "snowBerryStew", snowBerryPorridge);

        //Register Blocks
        registerBlock(rustedIronBlock, "rusted_iron_block", "rustedIronBlock");
        registerBlockAnvil(anvilRustedIron, "rusted_iron_anvil", "anvilRustedIron");
        registerBlockAnvil(anvilTungsten, "tungsten_anvil", "anvilTungsten");
        registerBlock(oreTungsten, "ore/tungsten_ore", "oreTungsten");
        registerBlock(blockTungsten, "block/tungsten_block", "blockTungsten");
        registerBlock(fenceTungsten, "bars/tungsten_bars", "fenceTungsten");
        registerBlock(doorTungsten, "door/door_tungsten", "doorTungsten");
        registerBlock(deepStaleBrick, "deepslate_brick", "deepStaleBrick");
        registerBlock(deepStaleMagma, "deepslate_brick_magma", "deepStaleMagma");
        registerBlock(cobbledDeepStale, "cobbled_deepslate", "cobbledDeepStale");
        registerBlock(stairsCobbleDeepSlate, "cobble_deepslate_stairs", "stairsCobbleDeepSlate");
        registerBlock(stairsDeepSlateBrick, "deepslate_brick_stairs", "stairsDeepSlateBrick");
        registerBlock(cobbleDeepStaleWall, "cobble_deepslate_wall", "cobbleDeepStaleWall");
        registerBlock(deepStaleBrickWall, "deepslate_brick_wall", "deepStaleBrickWall");
        registerBlock(gravelSand, "sand_gravel", "gravelSand");
        registerBlock(gravelDeepSlate, "deepslate_gravel", "gravelDeepSlate");
        registerBlock(deepSlate, "deepslate", "deepSlate");
        registerBlock(cobbledDeepStaleSingleSlab, "cobbledDeepslateSlab", "cobbledDeepslateSlab");
        registerBlock(cobbledDeepStaleDoubleSlab, "cobbledDeepslateSlab", "cobbledDeepslateSlab");
        registerBlock(deepStaleBrickSingleSlab, "deepslateBrickSlab", "deepslateBrickSlab");
        registerBlock(deepStaleBrickDoubleSlab, "deepslateBrickSlab", "deepslateBrickSlab");
        registerBlock(ancientRelict, "ancient_relict", "ancientRelict");
        registerBlock(tungstenWorkBench, "toolbench.tungsten", "toolbench.tungsten");
        registerBlock(oreIronDeepslate, "ore/normal/iron_ore_normal", "oreIronDeepslate");
        registerBlock(oreCoalDeepslate, "ore/normal/coal_ore_normal", "oreCoalDeepslate");
        registerBlock(oreLapisDeepslate, "ore/normal/lapis_ore_normal", "oreLapisDeepslate");
        registerBlock(oreDiamondDeepslate, "ore/normal/diamond_ore_normal", "oreDiamondDeepslate");
        registerBlock(oreEmeraldDeepslate, "ore/normal/emerald_ore_normal", "oreEmeraldDeepslate");
        registerBlock(oreCopperDeepslate, "ore/normal/copper_ore_normal", "oreCopperDeepslate");
        registerBlock(oreSilverDeepslate, "ore/normal/silver_ore_normal", "oreSilverDeepslate");
        registerBlock(oreMithrilDeepslate, "ore/normal/mithril_ore_normal", "oreMithrilDeepslate");
        registerBlock(oreAdamantiumDeepslate, "ore/normal/adamantium_ore_normal", "oreAdamantiumDeepslate");
        registerBlock(oreTungstenDeepslate, "ore/normal/tungsten_ore_normal", "oreTungstenDeepslate");
        registerBlock(oreGoldDeepslate, "ore/normal/gold_ore_normal", "oreGoldDeepslate");
        registerBlock(oreRedstoneDeepslate, "ore/normal/redstone_ore_normal", "oreRedstoneDeepslate");
        registerBlock(deepslateSilverFish, "monsterDeepslateEgg", "monsterDeepslateEgg");
        registerBlock(chestTungsten, "tungsten_chest", "chestTungsten");
        registerBlock(oreRedstoneDeepslateGlowing, "ore/normal/redstone_ore_normal", "oreRedstoneDeepslate");
        registerBlock(peachPlanks, "wood", "peachPlanks");
        registerBlock(peachWood, "log", "peachLogs");
        registerBlock(peachLeaves, "leaves_peach", "peachLeaves");
        registerBlock(peachSapling, "sapling", "peachSapling");
        registerBlock(peachPlanksSingleSlab, "wood", "woodSlab");
        registerBlock(peachPlanksDoubleSlab, "wood", "woodSlab");
        registerBlock(stairsPeachPlanks, "peach_planks_stairs", "stairsPeachPlanks");
        registerBlock(snowBerry, "bushes", "sonwBerry");
        registerBlock(basalt,"basalt","basalt");
    }

    static {
        rustedIronBlock = new BlockOreStorage(IdUtil.getNextBlockID(), Material.rusted_iron).setCreativeTab(tabCreationBlock);
        anvilRustedIron = (BlockAnvil) new BlockCTAnvil(IdUtil.getNextBlockID(), Material.rusted_iron).setStepSound(soundAnvilFootstep).setCreativeTab(tabCreationBlock);
        oreTungsten = (new BlockOre(IdUtil.getNextBlockID(), CTMaterials.tungsten, 4)).setHardness(3.25F).setResistance(15.0F).setCreativeTab(tabCreationBlock);
        blockTungsten = (new BlockOreStorage(IdUtil.getNextBlockID(), CTMaterials.tungsten)).setStepSound(soundMetalFootstep).setCreativeTab(tabCreationBlock);
        fenceTungsten = (new PaneBlock(IdUtil.getNextBlockID(), CreationModInit.RESOURCEID + "bars/tungsten_bars", CreationModInit.RESOURCEID + "bars/tungsten_bars", CTMaterials.tungsten, false)).setStepSound(soundMetalFootstep).setResistance(24.0F).setHardness(12.8F).setMinHarvestLevel(4).setCreativeTab(tabCreationBlock);
        doorTungsten = (new DoorBlock(IdUtil.getNextBlockID(), CTMaterials.tungsten, () -> Item.getItem(CTRegistryInit.doorTungsten))).setStepSound(soundMetalFootstep).setMinHarvestLevel(4).setCreativeTab(tabCreationBlock);
        anvilTungsten = (BlockAnvil) new BlockCTAnvil(IdUtil.getNextBlockID(), CTMaterials.tungsten).setStepSound(soundAnvilFootstep).setCreativeTab(tabCreationBlock);
        deepStaleBrick = (BlockCTDeepStaleBrick) (new BlockCTDeepStaleBrick(IdUtil.getNextBlockID())).setHardness(1.8F).setResistance(15.0F).setStepSound(soundDeepslateBrickFootstep).setCreativeTab(tabCreationBlock);
        deepStaleMagma = (BLockCTDeepSlateMagma) (new BLockCTDeepSlateMagma(IdUtil.getNextBlockID())).setHardness(1.8F).setResistance(15.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        cobbledDeepStale = (new BlockCTCobbledDeepSlate(IdUtil.getNextBlockID())).setHardness(2.5F).setResistance(15.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        stairsCobbleDeepSlate = (new StairsBlock(IdUtil.getNextBlockID(), cobbledDeepStale, 0)).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        stairsDeepSlateBrick = (new StairsBlock(IdUtil.getNextBlockID(), deepStaleBrick, 0)).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        cobbleDeepStaleWall = new WallBlock(IdUtil.getNextBlockID(), cobbledDeepStale).setHardness(2.5F).setResistance(15.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        deepStaleBrickWall = new WallBlock(IdUtil.getNextBlockID(), deepStaleBrick).setHardness(1.8F).setResistance(15.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        gravelSand = (BlockCTSandGravel) (new BlockCTSandGravel(IdUtil.getNextBlockID())).setHardness(0.6F).setStepSound(soundSandFootstep).setCreativeTab(tabCreationBlock);
        gravelDeepSlate = (BlockCTDeepSlateGravel) (new BlockCTDeepSlateGravel(IdUtil.getNextBlockID())).setHardness(0.8F).setStepSound(soundSandFootstep).setCreativeTab(tabCreationBlock);
        deepSlate = (new BlockCTDeepSlate(3348)).setHardness(3.0F).setResistance(15.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        cobbledDeepStaleSingleSlab = (BlockCTCobbleDeepSlateSlabGroup) (new BlockCTCobbleDeepSlateSlabGroup(IdUtil.getNextBlockID(), Material.stone)).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        cobbledDeepStaleDoubleSlab = (BlockCTDeepSlateDoubleSlab) (new BlockCTDeepSlateDoubleSlab(IdUtil.getNextBlockID(), cobbledDeepStaleSingleSlab)).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        deepStaleBrickSingleSlab = (BlockCTDeepSlateBrickSlabGroup) (new BlockCTDeepSlateBrickSlabGroup(IdUtil.getNextBlockID(), Material.stone)).setStepSound(soundDeepslateBrickFootstep).setCreativeTab(tabCreationBlock);
        deepStaleBrickDoubleSlab = (BlockCTDeepSlateDoubleSlab) (new BlockCTDeepSlateDoubleSlab(IdUtil.getNextBlockID(), deepStaleBrickSingleSlab)).setStepSound(soundDeepslateBrickFootstep).setCreativeTab(tabCreationBlock);
        ancientRelict = (BlockCTAncientRelict) new BlockCTAncientRelict(IdUtil.getNextBlockID()).setHardness(2.5F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        tungstenWorkBench = (WorkbenchBlock) new BlockCTWorkbench(IdUtil.getNextBlockID(), CTMaterials.tungsten, 0.55F, Material.ancient_metal).setStepSound(soundWoodFootstep).setCreativeTab(tabCreationBlock);
        oreIronDeepslate = (new BlockIronOreDeepslate(IdUtil.getNextBlockID(), Material.iron, 2)).setHardness(3.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreCoalDeepslate = (new BlockCoalOreDeepslate(IdUtil.getNextBlockID(), Material.coal, 2)).setHardness(1.2F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreLapisDeepslate = (new BlockLapisOreDeepslate(IdUtil.getNextBlockID(), Material.lapis_lazuli, 2)).setHardness(3.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreDiamondDeepslate = (new BlockDiamondOreDeepslate(IdUtil.getNextBlockID(), Material.diamond, 4)).setHardness(3.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreEmeraldDeepslate = (new BlockEmeraldOreDeepslate(IdUtil.getNextBlockID(), Material.emerald, 3)).setHardness(3.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreCopperDeepslate = (new BlockCopperOreDeepslate(IdUtil.getNextBlockID(), Material.copper, 2)).setHardness(2.5F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreSilverDeepslate = (new BlockSilverOreDeepslate(IdUtil.getNextBlockID(), Material.silver, 2)).setHardness(2.5F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreMithrilDeepslate = (new BlockMithrilOreDeepslate(IdUtil.getNextBlockID(), Material.mithril, 3)).setHardness(3.5F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreAdamantiumDeepslate = (new BlockAdamantiumOreDeepslate(IdUtil.getNextBlockID(), Material.adamantium, 4)).setHardness(4.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreTungstenDeepslate = (new BlockTungstenOreDeepslate(IdUtil.getNextBlockID(), CTMaterials.tungsten, 3)).setHardness(3.25F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreGoldDeepslate = (new BlockGoldOreDeepslate(IdUtil.getNextBlockID(), Material.gold, 2)).setHardness(2.4F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        oreRedstoneDeepslate = (new BlockRedstoneOreDeepslate(IdUtil.getNextBlockID(), false)).setHardness(3.0F).setResistance(5.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        deepslateSilverFish = (BlockCTDeepslateSilverFish) (new BlockCTDeepslateSilverFish(IdUtil.getNextBlockID())).setHardness(1.0F).setStepSound(soundDeepslateFootstep).setCreativeTab(tabCreationBlock);
        chestTungsten = new StrongBoxBlock(IdUtil.getNextBlockID(), CTMaterials.tungsten).setStepSound(soundMetalFootstep).setCreativeTab(tabCreationBlock);
        oreRedstoneDeepslateGlowing = (new BlockRedstoneOreDeepslate(IdUtil.getNextBlockID(), false)).setHardness(3.0F).setResistance(5.0F).setLightValue(0.625F).setStepSound(soundDeepslateFootstep);
        peachPlanks = (BlockCTWood) (new BlockCTWood(IdUtil.getNextBlockID())).setResistance(5.0F).setStepSound(soundWoodFootstep);
        peachWood = (BlockCTLog) (new BlockCTLog(IdUtil.getNextBlockID())).setStepSound(soundWoodFootstep);
        peachLeaves = (BlockCTLeaves) (new BlockCTLeaves(IdUtil.getNextBlockID())).setHardness(0.2f).setLightOpacity(1).setStepSound(soundGrassFootstep);
        peachSapling = (new BlockCTSapling(IdUtil.getNextBlockID())).setHardness(0.02F).setStepSound(soundGrassFootstep);
        peachPlanksSingleSlab = (BlockCTPeachPlanksSlabGroup) (new BlockCTPeachPlanksSlabGroup(IdUtil.getNextBlockID(), Material.wood)).setStepSound(soundWoodFootstep).setCreativeTab(tabCreationBlock);
        peachPlanksDoubleSlab = (BlockCTPeachPlanksDoubleSlab) (new BlockCTPeachPlanksDoubleSlab(IdUtil.getNextBlockID(), peachPlanksSingleSlab)).setStepSound(soundWoodFootstep).setCreativeTab(tabCreationBlock);
        stairsPeachPlanks = (new StairsBlock(IdUtil.getNextBlockID(), peachPlanks, 0)).setStepSound(soundWoodFootstep).setCreativeTab(tabCreationBlock);
        snowBerry = (BlockCTSnowBerry) (new BlockCTSnowBerry(IdUtil.getNextBlockID())).setHardness(0.05F).setStepSound(soundGrassFootstep).setCreativeTab(tabCreationBlock);
        basalt = new BlockStone(IdUtil.getNextBlockID()).setHardness(2.5f).setResistance(10.0f).setStepSound(soundStoneFootstep);
    }
}
